name: Update versions
on:
  schedule:
    - cron: '0 */12 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Install requirements
      run: python -m pip install -r requirements.txt
    - run: python updater.py
    - name: Commit
      run: |
        git config --local user.email ${{ secrets.GIT_EMAIL }}
        git config --local user.name ${{ secrets.GIT_NAME }}
        git commit -am "New BDS Version!"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
